# Generated by Django 5.2 on 2025-04-18 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plaid_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='plaid_integration.accesstoken')),
            ],
        ),
    ]
