# Generated by Django 5.2 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='cursor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
