# Generated by Django 5.2 on 2025-04-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accesstoken_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='icon_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
