# Generated by Django 5.2 on 2025-04-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_icon_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='icon_url',
            new_name='logo_url',
        ),
    ]
