# Generated by Django 5.2 on 2025-04-18 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plaid_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plaid_integration.accesstoken')),
            ],
        ),
    ]
